/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormBuilderIndexRouteImport } from './routes/form-builder/index'
import { Route as FormBuilderFormIdRouteImport } from './routes/form-builder/$formId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderIndexRoute = FormBuilderIndexRouteImport.update({
  id: '/form-builder/',
  path: '/form-builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormBuilderFormIdRoute = FormBuilderFormIdRouteImport.update({
  id: '/form-builder/$formId',
  path: '/form-builder/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/form-builder/$formId': typeof FormBuilderFormIdRoute
  '/form-builder': typeof FormBuilderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/form-builder/$formId': typeof FormBuilderFormIdRoute
  '/form-builder': typeof FormBuilderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/form-builder/$formId': typeof FormBuilderFormIdRoute
  '/form-builder/': typeof FormBuilderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$eventId'
    | '/form-builder/$formId'
    | '/form-builder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/$eventId' | '/form-builder/$formId' | '/form-builder'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId'
    | '/form-builder/$formId'
    | '/form-builder/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  FormBuilderFormIdRoute: typeof FormBuilderFormIdRoute
  FormBuilderIndexRoute: typeof FormBuilderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder/': {
      id: '/form-builder/'
      path: '/form-builder'
      fullPath: '/form-builder'
      preLoaderRoute: typeof FormBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form-builder/$formId': {
      id: '/form-builder/$formId'
      path: '/form-builder/$formId'
      fullPath: '/form-builder/$formId'
      preLoaderRoute: typeof FormBuilderFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  FormBuilderFormIdRoute: FormBuilderFormIdRoute,
  FormBuilderIndexRoute: FormBuilderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
